# Generated by Django 3.1.3 on 2020-12-01 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('isCheckIn', models.BooleanField(default=False)),
                ('isCheckOut', models.BooleanField(default=True)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register', to='member.member')),
            ],
        ),
    ]
